<center><img src="https://drive.google.com/uc?id=1JyBSeVdwey172waBwICufx0Iua67AEgP" width="500"></center>

#NumPy (Numerical Python)
Es una librería de Python que provee una serie de métodos para realizar operaciones matemáticas sobre una estructura de datos en forma de matriz (llamado **array**), que puede ser uni-dimensional (arreglo), bi-dimensional (matriz) o n-dimensional (tensores).
<center><img src="https://drive.google.com/uc?id=183gfGdH8rq4B84OmWBBsEnbrxmXMOeW6"></center>
Un array NumPy es un paquete de matrices N-dimensional que tienen forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.

Los arrays de NumPy son un formato común para intercambio de datos para muchas librerías de Python orientadas a datos, como Pandas y SciPy.
Los datos de un array:
* son homogéneos
* indexables
* extraíbles (slicing)

## Uso básico

###Crear un array de NumPy a partir de una lista
Para poder manipular una lista de Python con NumPy, es necesario convertirla en un ARREGLO o VECTOR con el método array() de NumPy.


In [ ]:
import numpy as np

lista = [34,67,45,34,23,45,78,90,6,4,23,45]
type(lista)
print(lista)

[34, 67, 45, 34, 23, 45, 78, 90, 6, 4, 23, 45]


In [ ]:
arr1 = np.array(lista)
print(arr1)

[34 67 45 34 23 45 78 90  6  4 23 45]


In [ ]:
arr1[8]

6

Un array es un objeto de tipo **numpy.ndarray** ($n$ significa "numeric" y $d$, "dimension")

###Matriz o arreglo bidimensional


###Acceder a los valores de un array/matriz
Para acceder a los elementos de un array unidimensional, se indica el índice, como en las lista de Python.
Para acceder a los elementos de un array bidimensional, se utiliza un sistema de coordenadas:  `array[{nro_fila}, {nro_columna}]`.

In [ ]:
lista2 = [[34,67,45,34],[23,45,78,90],[6,4,23,45]]
arr2 = np.array(lista2)
print(arr2)

[[34 67 45 34]
 [23 45 78 90]
 [ 6  4 23 45]]


In [ ]:
arr2[2,0]

6

###ACTIVIDAD A: Homogeneidad de datos en los array
1. Responder: ¿qué sucederá al convertir la siguiente lista de Python en un array de NumPy?


  ```
  lista_py = [1, "hora", 0.5, True, 34]
  array_np = np.array(lista_py)
  ```




In [ ]:
lista_py = [1, "hora", 0.5, True, 34]
array_np = np.array(lista_py)
print(array_np)

['1' 'hora' '0.5' 'True' '34']


In [ ]:
lista_py = [1, "hora", 0.5, True, [34]]
array_np = np.array(lista_py)
print(array_np)

#shape (x,)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

NumPy convierte todos los elementos de la lista en el tipo de dato más flexible disponible dentro de la lista. Si encuentra:
* un número decimal en una lista de enteros, convierte a todos en float.
* un valor True o False en una lista de enteros, lo convierte en su equivalente 1 ó 0.
* una cadena de texto en una lista con valores numéricos, todos se convierten en string.
* un objeto iterable (listas, tuplas, etc., aunque sean de un solo elemento), generará un error. Estos elementos no sólo difieren en tipo, sino en forma (shape para esta clase de objetos es del tipo `(x,)`, lo que hace imposible la conversión.
<br><br>

2. Crear ejemplos que demuestren los puntos que se acaban de enumerar.

###ACTIVIDAD B
Crear una lista con datos de tipo heterogéneo. Convertir esta lista:
1. en un vector
2. en una matriz de 3 filas x 4 columnas.¿Cuántos elementos debe tener la lista para poder generar esta matriz?

In [ ]:
lista3 = [False,1,2,3,4,5,6,7,8,9,10.5,11]
v1 = np.array(lista3)
print(v1)

[ 0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.5 11. ]


In [ ]:
lista4 = [[False,1,2,3],[4,5,6,7],[8,9,10.5,11]]
v2 = np.array(lista4)
print(v2)

[[ 0.   1.   2.   3. ]
 [ 4.   5.   6.   7. ]
 [ 8.   9.  10.5 11. ]]


###Atributos de los arreglos NumPy
Algunos de los atributos de los arreglos son
* size: devuelve un conteo de elementos en las filas y columnas del arreglo
* shape: devuelve la forma del arreglo
* dtype: devuelve el tipo de datos que contiene el arreglo.
* ndim: devuelve la cantidad de dimensiones del arreglo.

###ACTIVIDAD C
Crea y explora los atributos de un arreglo de números enteros de 2 dimensiones con 3 filas y 4 columnas.

In [ ]:
print(v2.size)
print(v2.shape)
print(v2.dtype)
print(v2.ndim)

12
(3, 4)
float64
2


###Cambio de tamaño y forma
El método numpy.reshape() permite modificar la forma de un arreglo.

Debemos asegurarnos que la cantidad de elementos del
arreglo sea el apropiado para obtener el formato deseado. Por ejemplo: un arreglo de 12 elementos, nos permite obtener arreglos de (1,12), (2,6), (3,4), (4,3), (6,2) o (12,1).



```
matriz = np.array([(8, 9, 10), (11, 12, 13)])
print(matriz)

matriz2 = matriz.reshape(3,2)
print(matriz2)

[[ 8  9 10]
 [11 12 13]]

[[ 8  9]
 [10 11]
 [12 13]]
```




###Cambio en el tipo de dato
Para convertir una lista de enteros a array de números decimales, redefinimos el atributo dtype:

`array1 = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float64) `

Si convertimos una lista de valores decimales a un array de enteros, el se trunca la parte decimal:

`array2 = np.array([[1.5, 2.3, 3.56, 4.88],[5.2, 6.85, 7.25, 8.3]],dtype=np.int64)`

NumPy puede definir el tipo de dato de un array de diferentes formas:
1. Implícita: analiza los datos y establece el tipo automáticamente.
```
a = np.array([0, 0, 1, 1, 0])  # Entero (int)
print(a)  # [0 0 1 1 0]
a.dtype  # dtype('int64')
```
```
a = np.array([0.1, 0.4, 1.0, 1.5, 0.9])  # Flotante (float)
print(a)  # [0.1 0.4 1.  1.5 0.9]
a.dtype  # dtype('float64')
```
```
a = np.array(['0', '0', '1', '1', '0'])  # Cadena Unicode (str)
print(a)  # ['0' '0' '1' '1' '0']
a.dtype  # dtype('<U1')
```
```
a = np.array([False, False, True, True, False])  # Booleano (bool)
print(a)  # [False False  True  True False]
a.dtype  # dtype('bool')
```

2. Con los tipos genéricos: Se establece asignando un tipo genérico Python al argumento dtype.
```
a = np.array([0, 0, 1, 1, 0], dtype=int)  # Entero (int)
print(a)  # [0 0 1 1 0]
a.dtype  # dtype('int64')
```
```
a = np.array([0.1, 0.4, 0.9], dtype=float)  # Flotante (float)
print(a)  # [0.1 0.4 0.9]
a.dtype  # dtype('float64')
```
```
a = np.array(['0', '0', '1', '1', '0'], dtype=str)  # Unicode (str)
print(a)  # ['0' '0' '1' '1' '0']
a.dtype  # dtype('<U1')
```
```
a = np.array([0, 0, 1, 1, 0], dtype=bool)  # Booleano (bool)
print(a)  # [False False  True  True False]
a.dtype  # dtype('bool')
```
3. Con los tipos de Numpy: Se establece asignando uno de los tipos de Numpy al argumento dtype.
```
a = np.array([0, 0, 1, 1, 0], dtype=np.int)
print(a)  # [0 0 1 1 0]
a.dtype  # dtype('int64')
```
4. Con los tipos abreviados: Los tipos abreviados son cadenas formadas por un carácter que representa el tipo y un número que expresa el tamaño o longitud del dato:
  * Booleanos: 'b1'.
  * Enteros: 'i1' (int8), 'i2' (int16), 'i4' (int32), 'i8' (int64).
  * Cadenas Unicode con distintas longitudes: 'u1', 'u2', 'u4', 'u8'.
  * Cadenas Bytes con distintas longitudes: 'S1', 'S2', 'S3', 'S4'.
  * Flotantes: 'f2' (float16), 'f4' (float32), 'f8' (float64).
  * Complejos: 'c8' (complex64), 'c16' (complex128).
  ```
  a = np.array([0, 0, 1, 1, 0], dtype='b1')  # Booleano (bool)
  print(a)  # [False False  True  True False]
  a.dtype  # dtype('bool')
```
```
  a = np.array([0, 0, 1, 1, 0], dtype='i1')  # Entero (int8)
  print(a)  # [0 0 1 1 0]
  a.dtype  # dtype('int8')
  ```

Al pie te dejamos material complementario sobre los tipos de datos en NumPy.



Para cambiar el tipo de dato de un arreglo ya existente, se utiliza el método numpy.astype(), que crea una copia del arreglo original con el tipo de dato especificado.
Ejemplo: Partiendo de la matriz:
```
[[ 1 10  3]
 [ 9  9 11]]
```
Podemos crear una copia con valores decimales con:
```
arr_float = arr_numeros.astype('float64')
```
```
[[ 1. 10.  3.]
 [ 9.  9. 11.]]
 ```

###ACTIVIDAD D
Convertir la matriz obtenida en la ACTIVIDAD C, en una matriz de números decimales, ordenados en 6 filas y 2 columnas.

In [ ]:
# RESUELVEN LOS ALUMNOS COMO EJERCITACIÓN

## MATERIAL COMPLEMENTARIO
* [NumPy Fundamentals](https://numpy.org/doc/stable/user/basics.html)
* [Data Types](https://numpy.org/devdocs/user/basics.types.html)

<hr>
<img src="https://drive.google.com/uc?id=16Fy8ub2YrUHJnQ8W2p3DrVI42b20ncXz" width="400">

**Todos los derechos son reservados por el Programa Codo a Codo perteneciente a la Dirección Agencia de Habilidades para el Futuro del Ministerio de Educación del Gobierno de la Ciudad Autónoma de Buenos Aires. Se encuentra prohibida su venta o comercialización.**