<center><img src="https://drive.google.com/uc?id=1JyBSeVdwey172waBwICufx0Iua67AEgP" width="500"></center>

##Arreglos especiales en NumPy

##Inicializando arreglos
En ocasiones se necesita crear arreglos que luego serán rellenados con datos.
Se pueden inicializar con ceros, valores espaciados uniformemente, valores constantes o aleatorios.



### Arreglo lleno de unos
El método numpy.ones() crea un arreglo lleno de unos. El tipo es float64.

`a1 = np.ones(3) `

`[1. 1. 1.]`
<br><br>
`# en arreglos de 2 dimensiones se utiliza doble paréntesis`

`a2 = np.ones((3, 5)) `

```
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
```

Puede convertirse en un matriz enteros:

`a3 = np.ones((3,5),dtype=np.int64)`

```
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```





### Arreglo lleno de ceros
`a4 = np.zeros((3,5),dtype=np.int64)`


```
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
```



### Arreglo lleno de un valor determinado


```
a5 = np.full((2,3),8) # SINTAXIS: numpy.full((filas,columnas), valor)
```
```
[[8 8 8]
 [8 8 8]]
```

<br>

`a6 = np.full((2,3),True)`
```
[[ True  True  True]
 [ True  True  True]]
```


###Arreglo lleno con valores equiespaciados
**numpy.arange()**

Crea un rango de valores enteros. Respeta la sintaxis de range() de Python.

Ejemplo: crear un arreglo con los valores comprendidos entre 0 y 50 a paso 5

In [ ]:
import numpy as np
eq1 = np.arange(0,51,5)
print(eq1)

[ 0  5 10 15 20 25 30 35 40 45 50]


**numpy.linspace()**
Toma el rango especificado y lo divide en n partes iguales. Este arreglo contiene valores tipo float.

Sintaxis: `numpy.linspace(min, max, n)`. A diferencia de arange(), linspace() toma el malor máximo y lo incluye en el arreglo.

Ejemplo 1: crear un arreglo con 5 valores que se encuentren entre 0 y 2

In [ ]:
eq2 = np.linspace(0,2,5)
print(eq2)

[0.  0.5 1.  1.5 2. ]


Ejemplo 2: crear un arreglo con 5 valores que se encuentren entre 2 y 10

In [ ]:
eq3 = np.linspace(2,10,5)
print(eq3)

[ 2.  4.  6.  8. 10.]


###Arreglo llenos con valores aleatorios
Numpy tiene un módulo que genera números aleatorios: random
().



**random.rand()**

Crea un arreglo con valores aleatorios con distribución uniforme en el intervalo [0,1).

Ejemplo 1: crear un arreglo de 200 valores aleatorios y explorar su distribución.

In [ ]:
r1 = np.random.rand(200)
print(r1)

[0.07819774 0.60430457 0.67332579 0.14469473 0.66006402 0.2113006
 0.39036344 0.37265193 0.94535769 0.05999625 0.08569716 0.9623832
 0.8894084  0.24830038 0.18156039 0.40509329 0.67649301 0.34382644
 0.2937951  0.82795172 0.75658547 0.51191538 0.26556808 0.3876538
 0.69463528 0.69508474 0.54532296 0.57639443 0.20693983 0.01830085
 0.90926693 0.97248782 0.21262068 0.08205363 0.10955163 0.07071126
 0.03838733 0.93062248 0.75226336 0.6057617  0.34274239 0.70738969
 0.97504131 0.19702191 0.37253476 0.46236356 0.56858208 0.42609242
 0.48506138 0.15340262 0.21712619 0.1668033  0.44454942 0.12488433
 0.75537517 0.13364492 0.16607429 0.64098339 0.78970093 0.4679167
 0.20695265 0.4972161  0.02254506 0.70909455 0.85385579 0.37158245
 0.83047715 0.57037436 0.62959528 0.40848032 0.67798773 0.22339101
 0.88947397 0.35847183 0.92776265 0.29924047 0.14751304 0.60275996
 0.25235664 0.97547014 0.13347757 0.29161694 0.38293652 0.65843802
 0.26674585 0.55869762 0.05777946 0.69847203 0.52753869 0.66829997

El método numpy.histogram() calcula los valores de un histograma, devolviendo dos arrays:
* valores enteros, mostrando la frecuencia de los datos
* los límites de los *bins* o barras.

Si enviamos los datos generados por numpy.random.rand() como argumento, veremos que el primer array devuelto por numpy.histogram() tiene valores bastante cercanos uno del otro. Esto significa que la distribución de los datos es uniforme: al graficar el histograma, no habría grandes diferencias en las alturas de las barras.

In [ ]:
np.histogram(r1, bins=10)

(array([18, 21, 17, 19, 24, 20, 23, 18, 19, 21]),
 array([0.00137239, 0.10075904, 0.20014569, 0.29953234, 0.39891898,
        0.49830563, 0.59769228, 0.69707893, 0.79646558, 0.89585223,
        0.99523888]))

Ejemplo 2: crear una matriz de 4 filas y 5 columnas de números aleatorios.

In [ ]:
np.random.rand(4,5)

array([[0.62156617, 0.10951127, 0.79493487, 0.70346084, 0.86612058],
       [0.45368121, 0.72221528, 0.31038808, 0.22913933, 0.86771392],
       [0.57369639, 0.77881412, 0.68176288, 0.32543717, 0.09714196],
       [0.40835964, 0.65488522, 0.12593269, 0.58029294, 0.81192987]])

**random.randn()**

Crea un arreglo con valores aleatorios con distribución normal en el intervalo [0,1).

Ejemplo 1: crear un arreglo de 200 valores aleatorios y explorar su distribución.

In [ ]:
r3= np.random.randn(200)
print(r3)

[-1.05515161e+00 -9.68279647e-01 -3.62050705e-01 -1.37180183e+00
 -1.62880827e+00  8.88004753e-01  1.21286675e+00  2.69192887e+00
 -1.65209352e+00  1.88693290e+00  1.25967489e+00 -3.21160870e-01
  9.95538244e-01 -2.73384356e-02  1.91237157e+00 -6.83158717e-02
  2.73366830e-01  1.04375235e+00  2.96551596e+00 -5.54154427e-01
 -3.71459428e-01 -7.59807970e-01  2.28193666e-01  1.23099306e+00
  4.53220110e-01  8.63696165e-01 -1.07448632e-01  1.81570502e+00
 -7.73274657e-01  3.75915979e-01  7.18284631e-01 -1.42533169e-01
  7.61968977e-01  6.58059787e-02 -8.82702528e-01  7.80102453e-01
  2.34777845e-01  1.05544104e+00 -1.24027040e+00  2.48334295e+00
  1.94071982e+00  2.22288233e+00 -1.54523841e+00  5.90584220e-02
  1.03485442e+00  6.06616258e-01  1.35637316e+00 -9.60070435e-01
 -7.95307539e-01 -4.21684246e-01  6.68094814e-02 -4.95706872e-01
  7.82925466e-01 -2.61657482e-02 -2.52085929e+00  3.08654999e-01
  4.04045719e-01 -1.32777153e+00  2.33932304e-01  1.25101343e-01
  1.40745388e+00  9.72401

In [ ]:
np.histogram(r3, bins=5)

(array([18, 45, 89, 37, 11]),
 array([-2.52085929, -1.42358424, -0.32630919,  0.77096586,  1.86824091,
         2.96551596]))

En este ejemplo, podemos ver cómo el método random.randn() creó una muestra con distribución gaussiana o normal.

Ejmeplo 2: crear un arreglo de 7 x 4 valores aleatorios

In [ ]:
'''
Matriz de dos por cuatro de muestras de la distribución normal con media 3 y desviación estándar 2,5:

3 + 2.5 * np.random.randn(2, 4)
array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677],   # random
       [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])  # random
'''

**random.randint()**

Devuelve un arreglo de números enteros aleatorios en el rango [inicio, final).

Ejemplo 1: generar un número aleatorio entre 1 y 99.

In [ ]:
np.random.randint(1,100)

68

Ejemplo 2: generar un arreglo de 10 elementos entre 1 y 99 en 10 filas y 2 columnas.

In [ ]:
# SINTAXIS: (inicio, final, (filas, columnas))
print(np.random.randint(1,100,(10,2)))

[[12 68]
 [74 17]
 [26 94]
 [78 11]
 [20 61]
 [78 10]
 [95 89]
 [41 17]
 [16 68]
 [43 27]]


Cada vez que ejecutamos una celda que genera valores aleatorios, los elementos obtenidos serán diferentes. Podemos evitarlo con random.seed(0).
Si te interesa saber más sobre cómo se generan los números aleatorios, podrás encontrar un link en material complementario.

In [ ]:


np.random.randint(1,100,(4,6))

array([[41, 16, 73, 23, 44, 83],
       [76,  8, 35, 50, 96, 76],
       [86, 48, 64, 32, 91, 21],
       [38, 40, 68,  5, 43, 52]])

In [ ]:
np.random.randint(1,100,(4,6))

array([[59, 24, 60,  3, 99, 63],
       [36, 95, 68, 83, 47, 21],
       [82, 51, 28, 15, 42, 59],
       [66, 37, 11, 87, 44, 12]])

###Matriz identidad
La matriz identidad es la matriz cuadrada que contiene 1 en su diagonal principal y 0 en el resto de las posiciones.

Exiten dos métodos en NumPy para generar estas matrices, con tipo float64: eye() e identity().

```
m1 = np.eye(4)
```
```
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```
<br>

```
mt = np.identity(4, dtype=np.int64)
```
```
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
```

##Operaciones matemáticas con arreglos
Es posible realizar operaciones aritméticas entre arreglos o entre un arreglo y un número.

Ejemplo 1:

```
arr1 = np.arange(10)
[0 1 2 3 4 5 6 7 8 9]

arr2 = np.arange(-5,5)
[-5 -4 -3 -2 -1  0  1  2  3  4]

arr1 + arr2
[-5 -3 -1  1  3  5  7  9 11 13]
```

Ejemplo 2: Para operar entre arreglos, ambos deben tener el mismo tamaño y forma
```
aa = np.arange(5)
[0 1 2 3 4]

bb = np.arange(10)
[0 1 2 3 4 5 6 7 8 9]

aa + bb[:5]
[0 2 4 6 8]
```
Ejemplo 3:
```
arr ** 3 # eleva al cubo
[  0   1   8  27  64 125 216 343 512 729]
```

##Slicing
Es posible crear nuevos arreglos a partir de la extracción de datos de un arreglo existente.
Utilizamos lo mismos criterios de sintaxis de range() de Python: `(inicio:tope:paso)`.

Ejemplo: Obtener los datos de las celdas:
* naranja
* turquesa
* rojo
* verde

<center><img src="https://drive.google.com/uc?id=1KPO3x8FEkRGxfcY21xuQHsPGBh2CJI-j">

In [ ]:
# CREO LA MATRIZ
matriz = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
print(matriz)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [ ]:
# BUSCO EL RANGO EN NARANJA
print(matriz[0,3:5])

[3 4]


In [ ]:
# BUSCO EL RANGO TURQUESA
print(matriz[4:,4:])

[[44 45]
 [54 55]]


In [ ]:
# BUSCO EL RANGO ROJO
print(matriz[:,2])

[ 2 12 22 32 42 52]


In [ ]:
# Si quiero que se imprima en columna, recuerdo que tengo el método reshape(filas,columnas)
print(matriz[:,2].reshape(6,1))

[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]


In [ ]:
# BUSCO EL RANGO VERDE
print(matriz[2::2,::2])

[[20 22 24]
 [40 42 44]]


##Actividad
1. Crear arreglo1, de 1 fila y 6 columnas con los datos 5,10,15,20,25,30

   Crear arreglo2, de 5 filas y 1 columna con los datos 100,200,300,400,500
   
   Crear arreglo3, a partir de arreglo2 - arreglo1

2. Usando slicing, obtener de arreglo3 los siguientes datos y cargarlos en arreglo4, arreglo5, arreglo6:

```
a.
[[ 285 280 275 ]
 [ 385 380 375 ]]

b.
[ 290 280 270 ]

c.
[[  75 ]
 [ 275 ]
 [ 475 ]]
```

In [ ]:
'''
Convertir dataframe (PANDAS) en csv
df.to_csv('/content/drive/My Drive/ejemplo.csv', index=False)
'''

##MATERIAL COMPLEMENTARIO
* [numpy.random.seed() explained](https://www.sharpsightlabs.com/blog/numpy-random-seed/)

<hr>
<img src="https://drive.google.com/uc?id=16Fy8ub2YrUHJnQ8W2p3DrVI42b20ncXz" width="400">

**Todos los derechos son reservados por el Programa Codo a Codo perteneciente a la Dirección Agencia de Habilidades para el Futuro del Ministerio de Educación del Gobierno de la Ciudad Autónoma de Buenos Aires. Se encuentra prohibida su venta o comercialización.**